kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingresses-list
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["watch", "list"]
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "watch", "list" ]